// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "finder":return img`
........................
.......fff..............
....fffff2f.............
..ffeeeee22ff...........
.ffeeeeee222ff..........
.feeeefffeeeef..........
.fffffeee2222ef.........
fffe222fffffe2f.........
fffffffffeeefff.....cc..
fefe44ebbf44eef...ccdc..
.fee4d4bbfddef..ccddcc..
..feee4dddddfeecdddc....
...f2222222eeddcdcc.....
...f444445e44ddccc......
...ffffffffeeee.........
...fff...ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "advice":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image3":
            case "key":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . c d 5 d c . . . . . 
. . . b c c d 5 5 5 d c c b . . 
. . b d d 5 5 5 5 5 5 5 d d b . 
. . . b c c d 5 5 5 d c c b . . 
. . . . . . c d 5 d c . . . . . 
. . . . . . . c 5 c . . . . . . 
. . . . . . . c d c . . . . . . 
. . . . . . . b d b . . . . . . 
. . . . . . . . b . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
